#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: N1_Single_Plus_Version

on:
  repository_dispatch:
    types: [single]
  workflow_dispatch:
  schedule:
    - cron: 0 04 * * 3

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: plus.config
  DIY_SH: diy.sh
  TZ: Asia/Shanghai
  RELEASE: true

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout æ£€æŸ¥é¡¹ç›®åˆ†æ”¯
      uses: actions/checkout@main

    - name: Initialization Environment å®‰è£…ç¼–è¯‘ç¯å¢ƒ
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-1804) tree
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
        
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
        sudo mkdir -p /upload
        sudo chown $USER:$GROUPS /upload
        
        cd /upload
        echo "UPLOAD=$PWD" >> $GITHUB_ENV
                
    - name: Clone source code ä¸‹è½½å›ºä»¶æºç 
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt 
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        cd openwrt
        
    - name: Update & Install Feeds ä¸‹è½½å®‰è£…æ’ä»¶
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
      
    - name: Load Custom Configuration åŠ è½½è‡ªå®šä¹‰è®¾ç½®
      run: |
        [ -e files ] && mv files openwrt/files
        chmod +x $DIY_SH
        cd openwrt
        $GITHUB_WORKSPACE/$DIY_SH        
     
    - name: SSH connection to Actions SSHé“¾æ¥ç®¡ç†
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: Compile Firmware ç¼–è¯‘å›ºä»¶
      id: compile
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        echo -e "$(nproc) thread compile"
        
        make -j$(nproc) || make -j1 || make -j1 V=s
        
        cp .config ${UPLOAD}/plus.config
        cd bin/targets/*/*
        cp openwrt-armvirt-64-default-rootfs.tar.gz  ${UPLOAD}/openwrt-armvirt-64-default-rootfs.tar.gz
        cp -r *.xz ${UPLOAD}/
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "FILE_TIME=$(date "+%Yå¹´%mæœˆ%dæ—¥-%Hç‚¹")" >> $GITHUB_ENV
        echo "::set-output name=status::success"       

    - name: Package OpenWrt with flippy script ä½¿ç”¨flippyè„šæœ¬æ‰“åŒ…
      uses: roacn/package-flippy-openwrt@main
      with:
        types: s905d
        out: ${{ env.UPLOAD }}
        openwrt-path: $GITHUB_WORKSPACE/openwrt/bin/targets/*/*
   
    - name: Create release å‘å¸ƒè‡³release
      if: steps.compile.outputs.status == 'success' && env.RELEASE == 'true' && !cancelled()
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.FILE_TIME }} ğŸš€ / N1_Single_Plus_Version | ç¼–è¯‘
        allowUpdates: true
        tag: N1_Single_Plus_Version_${{ env.FILE_DATE }}
        commit: master
        token: ${{ secrets.RELEASES_TOKEN  }}
        body: |
          é»˜è®¤IPï¼š192.168.1.2 é»˜è®¤å¯†ç ï¼š password
          å…¨æ–°åˆ·å…¥emmcæ–¹æ³•ï¼š
             1. å›ºä»¶åˆ·å…¥Uç›˜ã€‚
             2. cd root
             3. ./install-to-emmc.sh
             4. æ‹”æ‰Uç›˜ï¼Œæ–­ç”µé‡å¯ã€‚
        artifacts:  ${{ env.UPLOAD }}/*
        
    - name: Remove old Releases åˆ é™¤æ—§çš„release
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 6
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASES_TOKEN }}
